!function(){var w=window,d=w.document;if(w.onfocusin===undefined){d.addEventListener('focus',addPolyfill,true);d.addEventListener('blur',addPolyfill,true);d.addEventListener('focusin',removePolyfill,true);d.addEventListener('focusout',removePolyfill,true);}
function addPolyfill(e){var type=e.type==='focus'?'focusin':'focusout';var event=new CustomEvent(type,{bubbles:true,cancelable:false});event.c1Generated=true;e.target.dispatchEvent(event);}
function removePolyfill(e){if(!e.c1Generated){d.removeEventListener('focus',addPolyfill,true);d.removeEventListener('blur',addPolyfill,true);d.removeEventListener('focusin',removePolyfill,true);d.removeEventListener('focusout',removePolyfill,true);}
setTimeout(function(){d.removeEventListener('focusin',removePolyfill,true);d.removeEventListener('focusout',removePolyfill,true);});}}();var myCarousel=(function(){"use strict";var carousel,containerWidth,slides,slidesList,slidesDisplayed,index,slidenav,settings,timer,animationSuspended,announceItem,currentState;function forEachElement(elements,fn){for(var i=0;i<elements.length;i++)
fn(elements[i],i);}
function hasClass(el,className){if(el.classList){return el.classList.contains(className);}else{return new RegExp('(^| )'+className+'( |$)','gi').test(el.className);}}
function init(set){settings=set;currentState='waiting';carousel=set.element;slidesList=carousel.querySelector('.slides-list');slides=carousel.querySelectorAll('.slide');containerWidth=slidesList.offsetWidth;carousel.className+=' active';slidesDisplayed=0;var slidesWidthIteration=0;for(var i=0;i<slides.length;i++){var slideWidth=slides[i].offsetWidth;slides[i].style.width=slideWidth+'px';slidesWidthIteration+=slideWidth;if(slidesWidthIteration<=containerWidth){slidesDisplayed++;}}
if(slides.length<=slidesDisplayed){return;}
slidesList.style.width=slidesWidthIteration+'px';var btnPrev=document.createElement('div');btnPrev.className='controls';btnPrev.innerHTML='<button type="button" class="btn-prev">'+
'<img src="/themes/custom/total_com/dist/img/arrow-white-left.png" alt="'+Drupal.t('Show previous slide')+'">'+
'</button>';btnPrev.querySelector('.btn-prev').addEventListener('click',function(){prevSlide(true);});carousel.insertBefore(btnPrev,carousel.firstChild);var btnNext=document.createElement('div');btnNext.className='controls';btnNext.innerHTML='<button type="button" class="btn-next">'+
'<img src="/themes/custom/total_com/dist/img/arrow-white-right.png" alt="'+Drupal.t('Show next slide')+'">'+
'</button>';btnNext.querySelector('.btn-next').addEventListener('click',function(){nextSlide(true);});if(settings.slidenav||settings.animate){slidenav=document.createElement('ul');slidenav.className='slidenav bullet-points';if(settings.animate){var li=document.createElement('li');if(settings.startAnimated){li.innerHTML='<button class="btn-control" data-action="stop"><span class="sr-only">'+Drupal.t('Stop animation')+'</span>❚❚</button>';}else{li.innerHTML='<button class="btn-control" data-action="start"><span class="sr-only">'+Drupal.t('Start animation')+'</span><span class="btn-play"></span></button>';}
slidenav.appendChild(li);}
if(settings.slidenav){forEachElement(slides,function(el,i){var li=document.createElement('li');var klass=(i===0)?'class="current" aria-current="true" ':'';li.innerHTML='<button '+klass+'data-slide="'+i+'"><span class="sr-only">'+Drupal.t('Slide @number',{'@number':(i+1)})+'</span></button>';slidenav.appendChild(li);});}
slidenav.addEventListener('click',function(event){var button=event.target;if(button.localName=='button'){if(button.getAttribute('data-slide')){stopAnimation();setSlides(button.getAttribute('data-slide'));}else if(button.getAttribute('data-action')=='stop'){stopAnimation();}else if(button.getAttribute('data-action')=='start'){startAnimation();}}},true);carousel.className+=' with-slidenav';carousel.insertBefore(slidenav,carousel.firstChild);}
var liveregion=document.createElement('div');liveregion.setAttribute('aria-live','polite');liveregion.setAttribute('aria-atomic','true');liveregion.setAttribute('class','liveregion sr-only');carousel.appendChild(liveregion);carousel.insertBefore(btnNext,liveregion);carousel.addEventListener('mouseenter',suspendAnimation);carousel.addEventListener('mouseleave',function(event){if(animationSuspended){startAnimation();}});carousel.addEventListener('focusin',function(event){if(!hasClass(event.target,'slide')){suspendAnimation();}});carousel.addEventListener('focusout',function(event){if(!hasClass(event.target,'slide')&&animationSuspended){startAnimation();}});index=0;if(settings.startAnimated){timer=setTimeout(nextSlide,5000);}}
function setSlides(new_current,announceItemHere){if(currentState!=='waiting'){return;}
currentState='running';announceItem=typeof announceItemHere!=='undefined'?announceItemHere:false;new_current=parseFloat(new_current);for(var i=slides.length-1;i>=0;i--){slides[i].className='slide';}
var diff=new_current-index;if(new_current<0){new_current=slides.length-1;}
else if(new_current>=slides.length){new_current=0;}
var marginLeft=0;if(diff>0){for(var i=0;i<diff;i++){var slide2Move=index+i;if(slide2Move>=slides.length){slide2Move=0;}
if(settings.withAnimation){marginLeft-=slides[slide2Move].offsetWidth;}
else{slidesList.appendChild(slides[slide2Move]);}}
if(settings.withAnimation){var marginLeftIteration=marginLeft/settings.animationDuration*10,marginLeftIterate=0;var slidesListAnimation=setInterval(function(){marginLeftIterate+=marginLeftIteration;if(marginLeftIterate<=marginLeft){slidesList.style.marginLeft=marginLeft+'px';clearInterval(slidesListAnimation);for(var j=0;j<diff;j++){var slide2Move=index+j;if(slide2Move>=slides.length){slide2Move=0;}
slidesList.appendChild(slides[slide2Move]);}
slidesList.style.marginLeft=0;index=new_current;currentState='waiting';var otherSlides=slidesList.querySelectorAll('.slide:not(.current)');for(var i=slidesDisplayed-1;i<otherSlides.length;i++){otherSlides[i].setAttribute('aria-hidden','true');otherSlides[i].classList.add('visibility-hidden');}}
else{slidesList.style.marginLeft=marginLeftIterate+'px';}},10);}
else{slidesList.style.marginLeft=0;index=new_current;currentState='waiting';var otherSlides=slidesList.querySelectorAll('.slide:not(.current)');for(var i=slidesDisplayed-1;i<otherSlides.length;i++){otherSlides[i].setAttribute('aria-hidden','true');otherSlides[i].classList.add('visibility-hidden');}}}
else{var loopStart=index-1;if(loopStart<0){loopStart=slides.length-1;}
for(var i=loopStart;i>=new_current;i--){slidesList.insertBefore(slides[i],slidesList.firstChild);if(settings.withAnimation){marginLeft-=slides[i].offsetWidth;slidesList.style.marginLeft=marginLeft+'px';}}
if(settings.withAnimation){var marginLeftIteration=marginLeft/settings.animationDuration*10,marginLeftIterate=marginLeft;var slidesListAnimation=setInterval(function(){marginLeftIterate-=marginLeftIteration;if(marginLeftIterate>=0){slidesList.style.marginLeft=0;clearInterval(slidesListAnimation);index=new_current;currentState='waiting';var otherSlides=slidesList.querySelectorAll('.slide:not(.current)');for(var i=slidesDisplayed-1;i<otherSlides.length;i++){otherSlides[i].setAttribute('aria-hidden','true');otherSlides[i].classList.add('visibility-hidden');}}
else{slidesList.style.marginLeft=marginLeftIterate+'px';}},10);}
else{slidesList.style.marginLeft=0;index=new_current;currentState='waiting';var otherSlides=slidesList.querySelectorAll('.slide:not(.current)');for(var i=slidesDisplayed-1;i<otherSlides.length;i++){otherSlides[i].setAttribute('aria-hidden','true');otherSlides[i].classList.add('visibility-hidden');}}}
var slide2Display=new_current;for(var i=slidesDisplayed-1;i<slidesDisplayed;i++){slides[slide2Display].removeAttribute('aria-hidden');slides[slide2Display].classList.remove('visibility-hidden');if(++slide2Display>=slides.length){slide2Display=0;}}
slides[new_current].className+=' current';if(announceItem){carousel.querySelector('.liveregion').textContent='Item '+(new_current+1)+' of '+slides.length;}
if(settings.slidenav){var buttons=carousel.querySelectorAll('.slidenav button[data-slide]');for(var j=buttons.length-1;j>=0;j--){buttons[j].className='';buttons[j].removeAttribute('aria-current');buttons[j].innerHTML='<span class="sr-only">'+Drupal.t('Slide @number',{'@number':(j+1)})+'</span>';}
buttons[new_current].className="current active";buttons[new_current].innerHTML='<span class="sr-only">'+Drupal.t('Slide @number',{'@number':(new_current+1)})+'</span>';buttons[new_current].setAttribute('aria-current','true');}}
function nextSlide(announceItem){announceItem=typeof announceItem!=='undefined'?announceItem:false;setSlides(index+1,announceItem);if(settings.animate){timer=setTimeout(nextSlide,5000);}}
function prevSlide(announceItem){announceItem=typeof announceItem!=='undefined'?announceItem:false;setSlides(index-1,announceItem);}
function stopAnimation(){clearTimeout(timer);settings.animate=false;animationSuspended=false;var _this=carousel.querySelector('[data-action]');if(_this!==null){_this.innerHTML='<span class="sr-only">'+Drupal.t('Start animation')+'</span><span class="btn-play"></span>';_this.setAttribute('data-action','start');}}
function startAnimation(){settings.animate=true;animationSuspended=false;timer=setTimeout(nextSlide,5000);var _this=carousel.querySelector('[data-action]');if(_this!==null){_this.innerHTML='<span class="sr-only">'+Drupal.t('Stop animation')+'</span>❚❚';_this.setAttribute('data-action','stop');}}
function suspendAnimation(){if(settings.animate){clearTimeout(timer);settings.animate=false;animationSuspended=true;}}
return{init:init,next:nextSlide,prev:prevSlide,goto:setSlides,stop:stopAnimation,start:startAnimation};});;(function(Drupal,myCarousel){'use strict';Drupal.behaviors.carousel_init={attach:function(context){var carouselsSlideshow=context.getElementsByClassName('carousel-slideshow');for(var i=0;i<carouselsSlideshow.length;i++){var carousel=new myCarousel();carousel.init({element:carouselsSlideshow[i],slidenav:true,animate:true,withAnimation:true,animationDuration:600,startAnimated:true});if(window.matchMedia('(max-width: 576px)').matches){carouselsSlideshow[i].querySelector('.slide img').addEventListener('load',function(){var carousel=this.closest('.carousel-slideshow'),btns=carousel.querySelectorAll('.btn-prev, .btn-next');for(var ib=0;ib<btns.length;ib++){var imgHeight=carousel.querySelector('.slide img').offsetHeight;btns[ib].style.top=+Math.floor((imgHeight-btns[ib].offsetHeight)/2)+'px';}});}}
var carouselsPublication=context.getElementsByClassName('carousel-publication');for(var j=0;j<carouselsPublication.length;j++){var carousel=new myCarousel();carousel.init({element:carouselsPublication[j],slidenav:true,animate:true,withAnimation:true,animationDuration:400,startAnimated:true});}}};})(Drupal,myCarousel);;var searchAutocomplete=(function(){'use strict';const defaults={searchInput:'#search-input',completionUrl:'/callback',completionFilter:'search',minChars:1,highlight:true,displayCounter:true,resetValue:true};var settings;var searchInput;var searchReset;var lastFilter='';var lock=Date.now();var cache=[];var timeout=null;Plugin.fn=Plugin.prototype;var init=function(options){settings=Object.assign(defaults,options);searchInput=document.querySelector(settings.searchInput);if(searchInput!==null){var button=document.createElement('button');button.classList.add('visually-hidden');button.setAttribute('type','reset');button.setAttribute('tabindex',0);button.innerHTML='<img src="/themes/custom/total_com/dist/img/btn-close-popin.png" alt="'+Drupal.t('Reset')+'">';searchReset=button;searchInput.parentNode.insertBefore(button,searchInput.nextSibling)
searchInput.setAttribute('autocomplete','off');searchInput.setAttribute('aria-autocomplete','list');initEvents();}};var getCompletionWrapperId=function(){return settings.searchInput.replace('#','')+'-completion-wrapper';};var initEvents=function(){document.addEventListener('click',function(e){if(e.target.tagName.toLowerCase()!=='button'&&e.target.closest('#'+getCompletionWrapperId())===null){removeCompletion();searchReset.classList.add('visually-hidden');}});searchReset.addEventListener('click',function(e){e.preventDefault();if(settings.resetValue){searchInput.value='';}
removeCompletion();lock=Date.now();lastFilter='';});searchInput.addEventListener('keyup',function(e){if(e.keyCode===13){return;}
clearTimeout(timeout);timeout=setTimeout(function(){var filter=searchInput.value;if(filter.length<settings.minChars&&!searchReset.classList.contains('visually-hidden')){searchReset.classList.add('visually-hidden');removeCompletion();return;}
if(filter!==lastFilter){var lockRequest=lock=Date.now();lastFilter=filter;searchReset.classList.remove('visually-hidden');removeCompletion();if(cache[filter]!==undefined&&lockRequest===lock){displayList(cache[filter],filter);}
else{if(lockRequest===lock){var xhr=new XMLHttpRequest();xhr.open('GET',settings.completionUrl+'?'+settings.completionFilter+'='+filter,true);xhr.setRequestHeader('Content-Type','application/json');xhr.onreadystatechange=function(){if(xhr.readyState===4&&xhr.status===200){var json=JSON.parse(xhr.responseText);cache[filter]=json;if(lockRequest===lock){displayList(json,filter);}}};xhr.send();}}}},500);});};var displayList=function(list,filter){var div=document.createElement('div');div.id=getCompletionWrapperId();div.classList.add('completion-wrapper');if(settings.displayCounter){var counter=document.createElement('div');counter.classList.add('completion-counter');if(list.pager.total_items>0){counter.innerText=Drupal.formatPlural(list.pager.total_items,'@count result for @search','@count results for @search',{'@search':filter});}
else{counter.innerText=Drupal.t('@count result for @search',{'@count':list.pager.total_items,'@search':filter});}
div.appendChild(counter);}
var optionList=generateOptionList(list,filter);div.appendChild(optionList);removeCompletion();searchInput.parentNode.insertBefore(div,searchInput);};var highlightFilter=function(search,filter){var latinizeSearch=latinize(search),latinizeFilter=latinize(filter),regex=new RegExp('(?![^<]*>)('+latinizeFilter+')','ig'),matches=latinizeSearch.match(regex);if(matches!==null){for(var i=0;i<matches.length;i++){var pos=latinizeSearch.indexOf(matches[i],i>0?pos+1:0);var realPos=pos+i*7;search=search.substr(0,realPos)+'<b>'+search.substr(realPos,latinizeFilter.length)+'</b>'+search.substr(realPos+latinizeFilter.length);}}
return search;};var generateOptionList=function(items,filter){var list=document.createElement('ul');if(typeof items.rows!=='undefined'){items.rows.forEach(function(item){var li=document.createElement('li');if(settings.highlight){item.title=highlightFilter(item.title,filter);}
var link=document.createElement('a');link.setAttribute('href',item.url);link.innerHTML=item.title;li.appendChild(link);list.appendChild(li);});}
return list;};var removeCompletion=function(){var completion=document.getElementById(getCompletionWrapperId());if(completion!==null){completion.parentNode.removeChild(completion);}};return{init:init,getCompletionWrapperId:getCompletionWrapperId,};});;(function(Drupal,searchAutocomplete){'use strict';Drupal.behaviors.solr_search_autocomplete={attach:function(context,settings){var searchInput=context.querySelector('input[name="keys"]');if(searchInput!==null){var autocomplete=new searchAutocomplete();autocomplete.init({searchInput:'#edit-keys',completionUrl:'/'+drupalSettings.path.pathPrefix+'callback/search',completionFilter:'search',minChars:3,highlight:true,displayCounter:true,resetValue:false});var searchForm=document.getElementById('block-searchform'),resetButton=searchForm.querySelector('button[type="reset"]');document.querySelector('a.open-search').addEventListener('click',function(e){e.preventDefault();searchForm.classList.remove('hidden');searchForm.querySelector('input[type="text"]').focus();});document.addEventListener('click',function(e){resetButton.classList.remove('visually-hidden');if(e.target.closest('#header')===null||e.target.parentNode==resetButton){document.getElementById('block-searchform').classList.add('hidden');}});}}};})(Drupal,searchAutocomplete);;(function(Drupal){'use strict';Drupal.behaviors.total_stock_prices_header={attach:function(context,setting){var headerSettings=setting.total_stock_prices_header,stockExchanges=context.querySelectorAll('.total-stock-prices-header');if(stockExchanges.length>0){var xhr=[];for(var i=0;i<headerSettings.identifiers.length;i++){var ajaxUrl=headerSettings.url+'?ID='+headerSettings.identifiers[i]+'&LANG='+setting.path.currentLanguage;(function(i){xhr[i]=new XMLHttpRequest();xhr[i].open('GET',ajaxUrl);xhr[i].onload=function(){if(xhr[i].status===200){for(var j=0;j<stockExchanges.length;j++){stockExchanges[j].querySelector('.stock-prices-wrapper').innerHTML+=xhr[i].responseText;}}};xhr[i].send();})(i);}}}};})(Drupal);;(function(document,Drupal){'use strict';var btns=document.getElementsByClassName('btn-control-animation');for(var i=0;i<btns.length;i++){btns[i].addEventListener('click',function(){var wrapper=this.closest('.with-animation');if(wrapper.classList.contains('animation-paused')){wrapper.classList.remove('animation-paused');this.setAttribute('data-action','pause');this.setAttribute('aria-pressed','false');this.innerHTML='❚❚';}
else{wrapper.classList.add('animation-paused');this.setAttribute('data-action','start');this.setAttribute('aria-pressed','true');this.innerHTML='▶';}});}})(document,Drupal);;(function(){'use strict';var button=document.querySelector('.language-picker__button');var arrow=button.querySelector('.select-arrow');var list=document.querySelector('.header--interfacelang__list');list.style.display='none';button.addEventListener('click',function(event){event.stopPropagation();if(list.style.display==='none'){list.style.display='block';arrow.classList.add('select-arrow--active');}
else{list.style.display='none';arrow.classList.remove('select-arrow--active');}});document.addEventListener('click',function(event){var isButtonInside=button.contains(event.target),isClickInside=list.contains(event.target);if(!isButtonInside&&!isClickInside&&list.style.display==='block'){if(typeof(Event)==='function'){var newEvent=new Event('click');}
else{var newEvent=document.createEvent('Event');newEvent.initEvent('click',true,true);}
button.dispatchEvent(newEvent);}});})();;